<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit128b0549402588c4f1e826e2da266b28
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Stripe\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Stripe\\' => 
        array (
            0 => __DIR__ . '/..' . '/stripe/stripe-php/lib',
        ),
    );

    public static $prefixesPsr0 = array (
        'R' => 
        array (
            'Raven_' => 
            array (
                0 => __DIR__ . '/..' . '/sentry/sentry/lib',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit128b0549402588c4f1e826e2da266b28::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit128b0549402588c4f1e826e2da266b28::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit128b0549402588c4f1e826e2da266b28::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit128b0549402588c4f1e826e2da266b28::$classMap;

        }, null, ClassLoader::class);
    }
}
