<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'The file "{file}" is not an image.' => 'Fail "{file}" ei ole pildifail',
  'The image "{file}" height should be "{height}px".' => 'Pildi "{file}" kõrgus peab olema {height} pikselit.',
  'The image "{file}" height should be at least "{height}px".' => 'Pildi "{file}" kõrgus peab olema vähemalt {height} pikselit.',
  'The image "{file}" height should be at most "{height}px".' => 'Pildi "{file}" kõrgus võib olla kõige rohkem {height} pikseli.',
  'The image "{file}" mime type "{mime}" is not allowed.' => 'Pildi "{file}" tüüp "{mime}" ei ole lubatud.',
  'The image "{file}" width should be "{width}px".' => 'Pildi "{file}" laius peab olema {width} pikselit.',
  'The image "{file}" width should be at least "{width}px".' => 'Pildi "{file}" laius peab olema vähemalt {width} pikselit.',
  'The image "{file}" width should be at most "{width}px".' => 'Pildi "{file}" laius võib olla kõige rohkem {width} pikselit.',
  'The image "{file}" small side should be "{side}px".' => 'Pildi "{file}" väiksem külg peab olema {side} pikselit.',
  'The image "{file}" small side should be at least "{side}px".' => 'Pildi "{file}" väiksem külg peab olema vähemalt {side} pikselit.',
  'The image "{file}" small side should be at most "{side}px".' => 'Pildi "{file}" väiksem külg võib olla kõige rohkem {side} pikselit.',
  'The image "{file}" big side should be "{side}px".' => 'Pildi "{file}" suurem külg peab olema {side} pikselit.',
  'The image "{file}" big side should be at least "{side}px".' => 'Pildi "{file}" suurem külg peab olema vähemalt {side} pikselit.',
  'The image "{file}" big side should be at most "{side}px".' => 'Pildi "{file}" suurem külg võib olla kõige rohkem {side} pikselit.',
);
