<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '-All Articles-' => '-Kõik artiklid-',
  '2 Columns (30/70)' => '2 tulpa (30/70)',
  '2 Columns (50/50)' => '2 tulpa (50/50)',
  '2 Columns (70/30)' => '2 tulpa (70/30)',
  '3 Columns' => '3 tulpa',
  'Are you sure to delete this article?' => 'Kas olete kindel, et soovite kustutada selle artikli?',
  'Are you sure to delete this item?' => 'Kas olete kindel, et soovite kustutada selle rea?',
  'Article successfully created!' => 'Lisati uus artikkel!',
  'Article successfully updated!' => 'Artikkel muudetud!',
  'Articles' => 'Artiklid',
  'Cancel' => 'Loobu',
  'Create' => 'Lisa',
  'Fields with {mark} are required' => 'Tärniga {mark} märgitud väljad on kohustuslikud',
  'Insert Template' => 'Sisesta mall',
  'Manage' => 'Halda',
  'Manage Articles' => 'Halda artikleid',
  'Manage Menu' => 'Halda menüüd',
  'Menu successfully created!' => 'Lisati uus menüüpunkt!',
  'Menu successfully updated!' => 'Menüü muudetud!',
  'New Article' => 'Uus artikkel',
  'New Menu' => 'Uus menüüpunkt',
  'Save' => 'Salvesta',
  'Search' => 'Otsi',
  'Search Result' => 'Otsingu tulemused',
  'Update Article' => 'Muuda artiklit',
  'Update Menu' => 'Muuda menüüpunkti',
  'Up' => 'Üles',
);
